export type CatalogAsset = {
  creditProductId?: number | null;
  creditProduct?: import("@/features/credit-products/calculator").CreditProduct | null;
  categorySettings?: import("@/features/categories/settings").CategorySettings;
  id: number;
  slug: string;
  code: string;
  title: string;
  category: string;
  province?: string;
  city: string;
  district?: string | null;
  village?: string | null;
  address: string;
  price: number;
  oldPrice: number | null;
  land: number;
  building: number;
  bedrooms: number;
  image: string;
  photos?: string[];
  details?: import("@/features/aset/types").Asset["details"];
  viewCount?: number;
  interestCount?: number;
  auctionDate: string | null;
  certificate: string;
  description: string;
  saleMethod?: "Lelang" | "Jual Beli" | "Cessie";
};
