"use client";
import {useEffect,useState} from "react";
import {House,Building2,Trees,CarFront,Warehouse,Store,Landmark,Factory,KeyRound,Truck,MapPin,Hotel,Building,BriefcaseBusiness,ShoppingBag,BedDouble,Fence,LandPlot,Mountain,Wheat,Flower2,TreePine,Waves,Palmtree,Bike,BusFront,Caravan,Tractor,Ship,Plane,TrainFront,SquareParking,PanelsTopLeft,School,Hospital,Dumbbell,UtensilsCrossed,Coffee,Fuel,Wrench,Cog,Sun,Gavel} from "lucide-react";
import defaults from "./defaults.json";
import type {CategorySettings} from "./settings";
export const categoryIcons = {
  house: House,
  building: Building2,
  trees: Trees,
  car: CarFront,
  warehouse: Warehouse,
  store: Store,
  landmark: Landmark,
  factory: Factory,
  key: KeyRound,
  truck: Truck,
  map: MapPin,
  hotel: Hotel,
  apartment: Building,
  office: BriefcaseBusiness,
  shop: ShoppingBag,
  bed: BedDouble,
  fence: Fence,
  land: LandPlot,
  mountain: Mountain,
  farm: Wheat,
  garden: Flower2,
  forest: TreePine,
  water: Waves,
  beach: Palmtree,
  bike: Bike,
  bus: BusFront,
  van: Caravan,
  tractor: Tractor,
  ship: Ship,
  plane: Plane,
  train: TrainFront,
  parking: SquareParking,
  garage: PanelsTopLeft,
  school: School,
  hospital: Hospital,
  sports: Dumbbell,
  restaurant: UtensilsCrossed,
  cafe: Coffee,
  fuel: Fuel,
  tools: Wrench,
  machine: Cog,
  solar: Sun,
  auction: Gavel,
};
export const iconLabels: Record<string,string> = {
  house: "Rumah",
  building: "Gedung",
  trees: "Pohon",
  car: "Mobil",
  warehouse: "Gudang",
  store: "Toko",
  landmark: "Bangunan",
  factory: "Pabrik",
  key: "Kunci",
  truck: "Truk",
  map: "Lokasi",
  hotel: "Hotel",
  apartment: "Apartemen",
  office: "Kantor",
  shop: "Ruko",
  bed: "Penginapan",
  fence: "Kavling",
  land: "Tanah",
  mountain: "Pegunungan",
  farm: "Pertanian",
  garden: "Taman",
  forest: "Perkebunan",
  water: "Perairan",
  beach: "Wisata",
  bike: "Sepeda",
  bus: "Bus",
  van: "Karavan",
  tractor: "Traktor",
  ship: "Kapal",
  plane: "Pesawat",
  train: "Kereta",
  parking: "Parkir",
  garage: "Garasi",
  school: "Sekolah",
  hospital: "Rumah Sakit",
  sports: "Olahraga",
  restaurant: "Restoran",
  cafe: "Kafe",
  fuel: "SPBU",
  tools: "Peralatan",
  machine: "Mesin",
  solar: "Energi",
  auction: "Lelang",
};
export type Category = {name:string;label:string;icon:string;showHome:boolean;sortOrder:number;version:number;settings?:CategorySettings};
export function CategoryIcon({name,size=26}:{name:string;size?:number}) {const Icon=categoryIcons[name as keyof typeof categoryIcons]||Building2;return <Icon size={size} strokeWidth={1.6}/>;}
export function useCategories() {
 const [categories,setCategories]=useState<Category[]>(defaults.map(c=>({...c,version:1})));
 useEffect(()=>{const controller=new AbortController();fetch("/api/categories",{cache:"no-store",signal:controller.signal}).then(r=>{if(!r.ok) throw new Error();return r.json();}).then(setCategories).catch(()=>{});return ()=>controller.abort();},[]);
 return categories;
}
