export type Asset = {
  creditProductId?: number | null;
  id: number;
  slug: string;
  code: string;
  title: string;
  category: string;
  saleMethod: string;
  province: string | null;
  city: string;
  district?: string | null;
  village?: string | null;
  address: string;
  price: number;
  oldPrice: number | null;
  land: number;
  building: number;
  bedrooms: number;
  image: string;
  photos: string[];
  details?: {
    googleMapsUrl?: string;
    latitude?: number;
    locationIsDemo?: boolean;
    longitude?: number;
    attributes?: Record<string, string | number>;
    bathrooms?: number;
    floors?: number;
    electricity?: number;
    carport?: number;
    yearBuilt?: number;
    auctionDeposit?: number;
    auctionOrganizer?: string;
    auctionUrl?: string;
    facilities?: string[];
  };
  auctionDate: string | null;
  certificate: string;
  description: string;
  featured: number;
  archived: number;
};
export type AssetInput = Omit<Asset, "id" | "archived" | "featured"> & {
  featured: boolean;
};
